image: docker:latest

default:
  tags:
    - docker

services:
  - docker:dind

variables:
  DOCKER_TLS_CERTDIR: ""
  IMAGE_TAG: "${CI_COMMIT_SHORT_SHA}"
  RAILWAY_STATIC_URL: "http://186.158.152.12"
  PUBLIC_URL: "http://186.158.152.12"
  PORT: "3000"

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - docker build -t sms-sender:${IMAGE_TAG} .
  only:
    - main

deploy:
  stage: deploy
  script:
    - apk add --no-cache docker-compose
    - |
      export PORT=$(shuf -i 3000-3999 -n 1)  # Genera un puerto aleatorio entre 3000 y 3999
      echo "Asignando puerto: $PORT"
      sed -i "s/3000:3000/$PORT:3000/" docker-compose.yml  # Actualiza el puerto en docker-compose.yml
      docker-compose down || true
      docker-compose up -d
  only:
    - main